# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# init_image: rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.6.0

port_mappings:  
- "8888:8888" 

volume_mappings:
- "./data:/ryzers/data"
