# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

build_arguments:
#  - "GAZEBO_VERSION=harmonic"
#  - "GAZEBO_VERSION=ionic"   
  - "GAZEBO_VERSION=jetty"      

