# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# environment_variables:
# - "HSA_OVERRIDE_GFX_VERSION=11.0.0"  

port_mappings:
- "11434:11434"

volume_mappings:
- "$PWD/workspace/.ollama:/root/.ollama/"